version: '3.7'
services:
  postgres: 
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: athenkosi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: QuikNoteDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local